import { useState } from 'react'
import { NavLink, useLocation } from 'react-router-dom'
import { api } from '../../services/api'
import { useApi } from '../../hooks/useApi'
import ProjectSelector from './ProjectSelector'
import { Activity, Bell, ChevronDown, ChevronLeft, ChevronRight, Gauge, Menu, Network, Search, Settings, ShieldAlert, SlidersHorizontal, Waypoints, X } from 'lucide-react'
const links=[['Overview','/',Activity],['Traces','/traces',Waypoints],['Services','/services',Gauge],['Service Map','/service-map',Network],['Errors','/errors',ShieldAlert],['Performance','/performance',SlidersHorizontal],['Settings','/settings',Settings]]
export default function Layout({children,paused,setPaused}) { const [collapsed,setCollapsed]=useState(false),[mobile,setMobile]=useState(false); const health=useApi(()=>api.getHealth(),[]); const up=!health.error&&health.data?.status==='ok'; const dbUp=health.data?.database==='connected'; const location=useLocation(); const title=links.find(x=>x[1]===location.pathname)?.[0]||'Trace details'; const side=<aside className={`${collapsed?'w-[76px]':'w-60'} flex h-full flex-col border-r border-slate-800 bg-[#0b0f1a] p-3 transition-all duration-200`}><div className="mb-8 flex items-center gap-3 px-2 pt-2"><div className="grid h-8 w-8 shrink-0 place-items-center rounded-lg bg-gradient-to-br from-cyan-400 to-blue-600 font-bold text-slate-950">P</div>{!collapsed&&<span className="font-semibold tracking-tight">PulseTrace</span>}</div><nav className="space-y-1">{links.map(([name,to,Icon])=><NavLink end={to==='/'} to={to} key={name} onClick={()=>setMobile(false)} className="nav-item"> <Icon size={18}/>{!collapsed&&<span>{name}</span>}</NavLink>)}</nav><div className="mt-auto">{!collapsed&&<div className="mb-3 rounded-lg border border-cyan-500/15 bg-cyan-500/5 p-3 text-xs text-slate-400"><span className={`mb-1 block font-medium ${health.error?'text-rose-300':'text-cyan-300'}`}>{health.error?'Backend unreachable':health.loading?'Connecting…':up?'Backend connected':'Backend unavailable'}</span>{health.error?'Check the PulseTrace API':health.loading?'Checking API health':dbUp?'Database connected':'Database not connected'}</div>}<button onClick={()=>setCollapsed(!collapsed)} className="nav-item hidden w-full md:flex">{collapsed?<ChevronRight size={18}/>:<><ChevronLeft size={18}/><span>Collapse</span></>}</button></div></aside>
return <div className="min-h-screen bg-[#080b14] md:flex"> <div className="fixed inset-y-0 left-0 z-40 hidden md:block">{side}</div><div className="fixed inset-0 z-50 bg-black/60 md:hidden" style={{display:mobile?'block':'none'}} onClick={()=>setMobile(false)}><div className="h-full w-64" onClick={e=>e.stopPropagation()}>{side}</div></div><main className={`${collapsed?'md:ml-[76px]':'md:ml-60'} min-w-0 flex-1 transition-all`}><header className="sticky top-0 z-30 flex h-16 items-center gap-3 border-b border-slate-800 bg-[#080b14]/90 px-4 backdrop-blur md:px-7"><button className="md:hidden" onClick={()=>setMobile(true)}><Menu/></button><div className="min-w-0 flex-1"><p className="text-xs text-slate-500">Workspace / <span className="text-slate-400">Orbital Systems</span></p><h1 className="truncate text-lg font-semibold">{title}</h1></div><ProjectSelector/><button className="hidden items-center gap-1 rounded-lg border border-slate-700 px-2.5 py-2 text-xs text-slate-300 sm:flex">Production <ChevronDown size={14}/></button><div className="relative hidden lg:block"><Search size={15} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-500"/><input className="control w-52 pl-9" placeholder="Search anything..."/></div><button onClick={()=>setPaused(!paused)} className={`hidden rounded-full px-2.5 py-1 text-xs font-medium sm:block ${paused?'bg-slate-700 text-slate-300':'bg-emerald-500/10 text-emerald-300'}`}>{paused?'Paused':'● Live'}</button><button className="rounded-lg p-2 text-slate-400 hover:bg-slate-800"><Bell size={18}/></button><button className="grid h-8 w-8 place-items-center rounded-full bg-violet-500/20 text-xs font-semibold text-violet-200">AK</button></header><div className="p-4 md:p-7">{children}</div></main></div> }
