import { CheckCircle2, XCircle, AlertTriangle, Loader2, Search, X } from 'lucide-react'
export function Status({value}) { const cls=value==='success'||value==='Healthy'||value==='healthy'?'success':value==='error'||value==='Open'||value==='failing'?'error':'degraded'; const label=value==='success'?'Success':value==='error'?'Error':value; return <span className={`status ${cls}`}>{label}</span> }
export function Empty({title='Nothing to show', text='Try adjusting your filters.'}) { return <div className="py-12 text-center"><p className="font-medium text-slate-300">{title}</p><p className="mt-1 text-sm text-slate-500">{text}</p></div> }
export function Drawer({children,onClose}) { return <div className="fixed inset-0 z-50 bg-black/50 backdrop-blur-sm" onMouseDown={onClose}><aside className="absolute right-0 top-0 h-full w-full max-w-lg overflow-y-auto border-l border-slate-700 bg-[#101522] p-6 shadow-2xl" onMouseDown={e=>e.stopPropagation()}><button onClick={onClose} className="absolute right-5 top-5 rounded-md p-1 text-slate-400 hover:bg-slate-800"><X size={20}/></button>{children}</aside></div> }
export function SearchBox({value,onChange,placeholder='Search'}) { return <div className="relative"><Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-500"/><input value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder} className="control w-full pl-9" /></div> }
export const IconByKind=({kind})=>kind==='error'?<XCircle className="text-rose-400" size={16}/>:kind==='warn'?<AlertTriangle className="text-amber-400" size={16}/>:<CheckCircle2 className="text-emerald-400" size={16}/>
export function Loading({text='Loading…'}) { return <div role="status" className="flex items-center justify-center gap-3 py-16 text-sm text-slate-400"><Loader2 size={18} className="animate-spin text-cyan-400"/>{text}</div> }
export function ErrorState({error,onRetry}) { return <div role="alert" className="panel p-8 text-center"><AlertTriangle size={22} className="mx-auto text-amber-400"/><p className="mt-3 font-medium text-slate-200">{error?.network?'Backend unavailable':'Could not load data'}</p><p className="mx-auto mt-1 max-w-md text-sm text-slate-500">{error?.message||'Unexpected error.'}</p>{onRetry&&<button onClick={onRetry} className="control mt-4">Try again</button>}</div> }
export function NoTelemetry({projectName='this project',onRefresh,inline}) { return <div className={`${inline?'':'panel '}p-10 text-center`}><p className="font-medium text-slate-200">No telemetry received yet.</p><p className="mx-auto mt-1 max-w-md text-sm text-slate-500">Connect {projectName} to PulseTrace to start monitoring this application.</p>{onRefresh&&<button onClick={onRefresh} className="control mt-4">Check again</button>}</div> }
