import { useMemo } from 'react'
import { Bar, BarChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { api } from '../services/api'
import { durationHistogram, prettyName } from '../services/adapters'
import { useApi } from '../hooks/useApi'
import { Empty, ErrorState, Loading, NoTelemetry } from '../components/common/UI'
import { useProject } from '../context/ProjectContext'
import { fmt, ms } from '../utils/formatters'
const load=async projectId=>{const [performance,traces]=await Promise.all([api.getPerformance({projectId}),api.getTraces({projectId,limit:100})]);return {performance:performance.data,traces:traces.data}}
export default function Performance(){const {projectId,project}=useProject();const {data,error,reload}=useApi(()=>load(projectId),[projectId]);const histogram=useMemo(()=>data?durationHistogram(data.traces.map(t=>t.duration)):[],[data])
if(error)return <ErrorState error={error} onRetry={reload}/>
if(!data)return <Loading text="Loading performance metrics…"/>
const p=data.performance;const endpoints=p.slowestEndpoints;
if(!data.traces.length&&!p.slowestServices.length&&!endpoints.length)return <NoTelemetry projectName={project?.name} onRefresh={reload}/>
const bottlenecks=p.slowestServices.slice(0,3)
return <div className="space-y-5"><section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[['Average latency',ms(p.averageLatency)],['P50 latency',ms(p.p50)],['P95 latency',ms(p.p95)],['P99 latency',ms(p.p99)]].map(x=><div className="metric" key={x[0]}><p className="label">{x[0]}</p><p className="metric-value">{x[1]}</p><p className="mt-1 text-xs text-slate-500">Across all recorded traces</p></div>)}</section><section className="grid gap-5 xl:grid-cols-5"><article className="panel p-5 xl:col-span-3"><h2 className="font-medium">Request duration distribution</h2><p className="mt-1 text-sm text-slate-500">Latency across the latest {data.traces.length} completed traces</p><div className="mt-4 h-64">{histogram.length?<ResponsiveContainer><BarChart data={histogram}><XAxis dataKey="range" tick={{fill:'#64748b',fontSize:10}} axisLine={false} tickLine={false}/><YAxis allowDecimals={false} tick={{fill:'#64748b',fontSize:10}} axisLine={false} tickLine={false}/><Tooltip contentStyle={{background:'#101522',border:'1px solid #334155'}} formatter={v=>[`${v} traces`,'Count']}/><Bar dataKey="count" fill="#8b5cf6" radius={[4,4,0,0]}/></BarChart></ResponsiveContainer>:<Empty title="No traces yet" text="The distribution appears once traces are recorded."/>}</div></article><article className="panel p-5 xl:col-span-2"><h2 className="font-medium">Bottlenecks</h2><p className="mt-1 text-sm text-slate-500">Slowest services by average span latency</p><div className="mt-4 space-y-3">{!bottlenecks.length&&<Empty title="No span data" text="Record spans to see bottlenecks."/>}{bottlenecks.map(s=><div className="soft-panel p-3" key={s.serviceName}><p className="text-sm">{prettyName(s.serviceName)}</p><div className="mt-1 flex justify-between text-xs"><span className="text-rose-300">{ms(s.averageLatency)} avg · {ms(s.p95)} p95</span><span className="text-slate-500">{fmt(s.requestCount)} spans</span></div></div>)}</div></article></section><article className="panel overflow-hidden"><div className="p-5"><h2 className="font-medium">Slowest endpoints</h2></div><div className="overflow-x-auto"><table className="w-full min-w-[600px]"><thead><tr><th className="table-head px-5 pb-3">Endpoint</th><th className="table-head pb-3">Service</th><th className="table-head pb-3">Avg duration</th><th className="table-head pb-3">P95 duration</th><th className="table-head pb-3">Requests</th></tr></thead><tbody>{endpoints.map(e=><tr className="table-row" key={e.operation}><td className="px-5 py-4 font-mono text-xs text-cyan-200">{e.operation}</td><td>{prettyName(e.serviceName)}</td><td>{ms(e.averageLatency)}</td><td className="text-amber-300">{ms(e.p95)}</td><td>{fmt(e.requestCount)}</td></tr>)}</tbody></table>{!endpoints.length&&<Empty title="No endpoint data" text="Endpoints appear once traces are recorded."/>}</div></article></div>}
