import { useMemo,useState } from 'react'
import { api } from '../services/api'
import { adaptServices } from '../services/adapters'
import { useApi } from '../hooks/useApi'
import { Drawer, Empty, ErrorState, Loading, NoTelemetry, SearchBox, Status } from '../components/common/UI'
import { useProject } from '../context/ProjectContext'
import { fmt, ms,pct } from '../utils/formatters'
const load=async projectId=>{const [services,map,performance]=await Promise.all([api.getServices({projectId}),api.getServiceMap({projectId}),api.getPerformance({projectId})]);return adaptServices(services.data,map.data.nodes,performance.data.slowestServices)}
export default function Services(){const [q,setQ]=useState(''),[sel,setSel]=useState(),[sort,setSort]=useState('requests');const {projectId,project}=useProject();const {data,error,reload}=useApi(()=>load(projectId),[projectId]);const rows=useMemo(()=>(data||[]).filter(s=>s.name.toLowerCase().includes(q.toLowerCase())).sort((a,b)=>sort==='errorPct'?b.errorPct-a.errorPct:b[sort]-a[sort]),[data,q,sort])
if(error)return <ErrorState error={error} onRetry={reload}/>
if(!data)return <Loading text="Loading services…"/>
if(!data.length)return <NoTelemetry projectName={project?.name} onRefresh={reload}/>
return <div className="space-y-5"><div className="flex flex-wrap gap-3"><div className="w-full sm:w-80"><SearchBox value={q} onChange={setQ} placeholder="Filter services"/></div><select className="control" value={sort} onChange={e=>setSort(e.target.value)}><option value="requests">Sort by requests</option><option value="latency">Sort by latency</option><option value="errorPct">Sort by error rate</option></select></div>{!rows.length&&<div className="panel"><Empty title={data.length?'No matching services':'No services yet'} text={data.length?'Try a different filter.':'Services appear once spans are recorded.'}/></div>}<div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{rows.map(s=><button key={s.id} onClick={()=>setSel(s)} className="panel p-5 text-left transition hover:-translate-y-0.5 hover:border-slate-700"><div className="flex items-start justify-between"><div><i className="mr-2 inline-block h-2.5 w-2.5 rounded-full" style={{background:s.color}}/><span className="font-medium">{s.name}</span></div><Status value={s.health}/></div><div className="mt-5 grid grid-cols-3 gap-2"><div><p className="label">Requests</p><p className="mt-1 text-sm">{fmt(s.requests)}</p></div><div><p className="label">Error</p><p className="mt-1 text-sm">{pct(s.errorPct)}</p></div><div><p className="label">P95</p><p className="mt-1 text-sm">{s.p95==null?'—':ms(s.p95)}</p></div></div><div className="mt-5 h-1.5 overflow-hidden rounded-full bg-slate-800"><i className="block h-full rounded-full" style={{width:`${Math.min(100,s.errorPct)}%`,background:'#fb7185'}}/></div><p className="mt-2 text-xs text-slate-500">Avg latency {ms(s.latency)} · {s.environment}</p></button>)}</div>{sel&&<Drawer onClose={()=>setSel(null)}><p className="label">Service details</p><h2 className="mt-2 text-xl font-semibold">{sel.name}</h2><div className="mt-3"><Status value={sel.health}/></div><div className="mt-6 grid grid-cols-2 gap-3">{[['Requests',fmt(sel.requests)],['Average latency',ms(sel.latency)],['P95 latency',sel.p95==null?'—':ms(sel.p95)],['Error rate',pct(sel.errorPct)],['Errors',fmt(sel.errors)],['Environment',sel.environment]].map(x=><div className="soft-panel p-3" key={x[0]}><p className="label">{x[0]}</p><p className="mt-1 font-medium">{x[1]}</p></div>)}</div><div className="mt-6 soft-panel p-4 text-sm"><p className="label">Registered</p><p className="mt-2">{sel.createdAt?new Date(sel.createdAt).toLocaleString():'—'}</p></div></Drawer>}</div>}
