import { useMemo, useState } from 'react'
import { Background, Controls, Handle, MiniMap, Position, ReactFlow, useEdgesState, useNodesState } from '@xyflow/react'
import '@xyflow/react/dist/style.css'
import { api } from '../services/api'
import { adaptServiceMap } from '../services/adapters'
import { useApi } from '../hooks/useApi'
import { Drawer, ErrorState, Loading, NoTelemetry, Status } from '../components/common/UI'
import { useProject } from '../context/ProjectContext'
import { fmt, ms, pct } from '../utils/formatters'
function Node({data}){return <div className="min-w-44 rounded-xl border border-slate-700 bg-[#111827] p-3 shadow-xl" style={{borderLeftColor:data.service.color,borderLeftWidth:3}}><Handle type="target" position={Position.Left}/><div className="flex items-center justify-between"><span className="text-sm font-medium">{data.service.name}</span><span className={`h-2 w-2 rounded-full ${data.service.health==='healthy'?'bg-emerald-400':data.service.health==='failing'?'bg-rose-400':'bg-amber-400'}`}/></div><div className="mt-2 flex gap-3 text-[11px] text-slate-400"><span>{fmt(data.service.requests)} req</span><span>{data.service.errorPct.toFixed(1)}% err</span></div><Handle type="source" position={Position.Right}/></div>}
const nodeTypes={service:Node}
function Graph({graph}){const [nodes,,onNodesChange]=useNodesState(graph.nodes);const [edges,,onEdgesChange]=useEdgesState(graph.edges);const [sel,setSel]=useState();return <><div className="panel h-[650px] overflow-hidden"><ReactFlow nodes={nodes} edges={edges} nodeTypes={nodeTypes} onNodesChange={onNodesChange} onEdgesChange={onEdgesChange} onNodeClick={(_,n)=>setSel(n.data.service)} fitView minZoom={.5}><Background color="#263146" gap={22}/><Controls/><MiniMap nodeColor={n=>n.data?.service?.color||'#334155'} maskColor="rgba(8,11,20,.7)"/></ReactFlow></div>{sel&&<Drawer onClose={()=>setSel(null)}><p className="label">Dependency service</p><h2 className="mt-2 text-xl font-semibold">{sel.name}</h2><div className="mt-3"><Status value={sel.health}/></div><div className="mt-6 space-y-3">{[['Requests',fmt(sel.requests)],['Error rate',pct(sel.errorPct)],['Average latency',ms(sel.latency)],['Environment',sel.environment||'—']].map(x=><div className="soft-panel flex justify-between p-3" key={x[0]}><span className="text-sm text-slate-400">{x[0]}</span><span className="text-sm">{x[1]}</span></div>)}</div></Drawer>}</>}
export default function ServiceMap(){const {projectId,project}=useProject();const {data,error,reload}=useApi(()=>api.getServiceMap({projectId}),[projectId]);const graph=useMemo(()=>data?adaptServiceMap(data.data):null,[data])
return <div className="space-y-4"><div className="flex items-center justify-between"><p className="text-sm text-slate-500">Service dependency topology · click a service for detail</p><div className="flex gap-3 text-xs"><span className="text-emerald-300">● Healthy</span><span className="text-amber-300">● Degraded</span><span className="text-rose-300">● Failing</span></div></div>{error?<ErrorState error={error} onRetry={reload}/>:!graph?<Loading text="Loading service map…"/>:!graph.nodes.length?<NoTelemetry projectName={project?.name} onRefresh={reload}/>:<Graph graph={graph}/>}</div>}
