import { useEffect, useMemo, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { api } from '../services/api'
import { adaptTrace } from '../services/adapters'
import { ms, timeAgo } from '../utils/formatters'
import { Empty, ErrorState, Loading, NoTelemetry, SearchBox, Status } from '../components/common/UI'
import { useProject } from '../context/ProjectContext'
const PAGE_SIZE=20
export default function Traces(){const [q,setQ]=useState(''),[status,setStatus]=useState('all'),[sort,setSort]=useState('time');const [rows,setRows]=useState([]),[pagination,setPagination]=useState(null),[loading,setLoading]=useState(true),[loadingMore,setLoadingMore]=useState(false),[error,setError]=useState(null),[nonce,setNonce]=useState(0);const nav=useNavigate();const {projectId,project}=useProject()
useEffect(()=>{let cancelled=false;setLoading(true);setError(null);const timer=setTimeout(()=>{api.getTraces({projectId,page:1,limit:PAGE_SIZE,...(status!=='all'&&{status}),...(q.trim()&&{search:q.trim()})}).then(r=>{if(cancelled)return;setRows(r.data.map(adaptTrace));setPagination(r.pagination);setLoading(false)},e=>{if(cancelled)return;setError(e);setLoading(false)})},q?300:0);return()=>{cancelled=true;clearTimeout(timer)}},[q,status,nonce,projectId])
const loadMore=()=>{setLoadingMore(true);api.getTraces({projectId,page:pagination.page+1,limit:PAGE_SIZE,...(status!=='all'&&{status}),...(q.trim()&&{search:q.trim()})}).then(r=>{setRows(x=>[...x,...r.data.map(adaptTrace)]);setPagination(r.pagination)},setError).finally(()=>setLoadingMore(false))}
const shown=useMemo(()=>sort==='duration'?[...rows].sort((a,b)=>b.duration-a.duration):rows,[rows,sort])
const hasMore=pagination&&pagination.page<pagination.totalPages
return <div className="space-y-5"><div className="panel p-4"><div className="grid gap-3 md:grid-cols-4"><SearchBox value={q} onChange={setQ} placeholder="Search trace ID, service, or route"/><select className="control" value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All statuses</option><option value="success">Success</option><option value="error">Error</option></select><select className="control" value={sort} onChange={e=>setSort(e.target.value)}><option value="time">Newest first</option><option value="duration">Longest duration</option></select><select className="control"><option>All methods</option><option>GET</option><option>POST</option></select></div></div>{error?<ErrorState error={error} onRetry={()=>setNonce(n=>n+1)}/>:<article className="panel overflow-hidden"><div className="p-5"><h2 className="font-medium">Trace explorer</h2><p className="mt-1 text-sm text-slate-500">{loading?'Loading traces…':`${pagination?.total??0} matching traces`}</p></div>{loading?<Loading text="Loading traces…"/>:<><div className="overflow-x-auto"><table className="w-full min-w-[790px]"><thead><tr><th className="table-head px-5 pb-3">Trace ID</th><th className="table-head pb-3">Request</th><th className="table-head pb-3">Root service</th><th className="table-head pb-3">Duration</th><th className="table-head pb-3">Status</th><th className="table-head pb-3">Timestamp</th></tr></thead><tbody>{shown.map(t=><tr key={t.id} onClick={()=>nav(`/traces/${encodeURIComponent(t.id)}`)} className="table-row cursor-pointer"><td className="px-5 py-4 font-mono text-xs text-cyan-300">{t.id}</td><td><span className="mr-2 text-xs text-violet-300">{t.method}</span>{t.route}</td><td>{t.service}</td><td>{ms(t.duration)}</td><td><Status value={t.status}/></td><td className="text-slate-500" title={new Date(t.timestamp).toLocaleString()}>{timeAgo(t.timestamp)}</td></tr>)}</tbody></table>{!shown.length&&(q||status!=='all'?<Empty title="No traces found" text="Try adjusting your filters."/>:<NoTelemetry inline projectName={project?.name} onRefresh={()=>setNonce(n=>n+1)}/>)}</div>{hasMore&&<div className="border-t border-slate-800 p-4 text-center"><button className="text-sm text-cyan-300" disabled={loadingMore} onClick={loadMore}>{loadingMore?'Loading…':'Load more traces'}</button></div>}</>}</article>}</div> }
