import { Routes, Route, Navigate } from 'react-router-dom'
import { useState } from 'react'
import Layout from './components/layout/Layout'
import Overview from './pages/Overview'
import Traces from './pages/Traces'
import TraceDetails from './pages/TraceDetails'
import Services from './pages/Services'
import ServiceMap from './pages/ServiceMap'
import Errors from './pages/Errors'
import Performance from './pages/Performance'
import Settings from './pages/Settings'
import { useLiveData } from './hooks/useLiveData'
import { ProjectGate, ProjectProvider } from './context/ProjectContext'
export default function App(){const [paused,setPaused]=useState(false);const tick=useLiveData(paused);return <ProjectProvider><Layout paused={paused} setPaused={setPaused}><ProjectGate><Routes><Route path="/" element={<Overview tick={tick}/>}/><Route path="/traces" element={<Traces/>}/><Route path="/traces/:id" element={<TraceDetails/>}/><Route path="/services" element={<Services/>}/><Route path="/service-map" element={<ServiceMap/>}/><Route path="/errors" element={<Errors/>}/><Route path="/performance" element={<Performance/>}/><Route path="/settings" element={<Settings/>}/><Route path="*" element={<Navigate to="/" replace/>}/></Routes></ProjectGate></Layout></ProjectProvider>}
